name: Deploy Cloud Portfolio

on:
  push:
    branches:
      - main  # Trigger workflow only on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Change if your region is different

      - name: Initialize Terraform
        run: terraform init

      # ✅ Import the existing S3 bucket
      - name: Import S3 bucket if not in state
        run: terraform import module.s3.aws_s3_bucket.main tf-portfolio-saksham-cloud || true

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve
